### ISSUE TITLE
pdb_redo data

### ISSUE THREAD

**Issue by BSharmi** [smiles724/VQMAE#3]
Hello!

Sorry another question :)
I downloaded the pdb-redo and there seems to be so many folders with cif. In the VQMAE file the pdb-redo is defined as below
```
data:
  pdbredo_dir: ./data/pdb_redo/cif
  clusters_path: ./data/pdbredo_clusters.txt
  splits_path: ./data/pdbredo_splits.txt
  processed_dir: ./data/PDB_REDO_processed
```
Would you please explain a bit how did you do the clustering, splits and created the processed dataset?

Thank you very much,
Sharmi
